### PR TITLE
Return "truth catalog" info

### PR DESCRIPTION
**Pull request by zhouconghao**
`make_exp` returns ra, dec, and redshift of simulated objects. As mentioned in this [issue](https://github.com/LSSTDESC/descwl-shear-sims/issues/129).

### CODE REVIEW

**Comment by zhouconghao** [comment]
Sorry incidentally also include [another PR](https://github.com/LSSTDESC/descwl-shear-sims/pull/207) in this. I can try to revert it if needed.

**Comment by zhouconghao** [comment]
> The change of `se_wcs` to a dict is a breaking change. I do think it should have its own PR

Thanks Erin! I have already submitted a [PR](https://github.com/LSSTDESC/descwl-shear-sims/pull/207) on returning `se_wcs` here. Maybe this PR can be merged first to avoid rebasing? Happy to modify the code too as it's not too much.

**Review by esheldon — APPROVED** [review]
This looks good to me.

In the future when submitting PRs please do not run "black".  It makes a large number of unnecessary changes.

**Comment by zhouconghao** [comment]
> This looks good to me.
> 
> In the future when submitting PRs please do not run "black". It makes a large number of unnecessary changes.

Got it! Thanks!

**Pull request merged**
