### PR TITLE
make galsim draw method optional, default auto

### PR DESCRIPTION
**Pull request by esheldon**

### CODE REVIEW

**Comment by esheldon** [comment]
I think just turning on 'phot' is correct because wldeblend gives flux in electrons

However, it can use a ton of memory so probably want to put a cap on number of photons

**Comment by esheldon** [comment]
This gets pretty slow in some cases if there are objects with a lot of photons.

Because we are drawing all objects at once (other than BRIGHT) we can't control this by using fewer photons in some cases.

**Comment by esheldon** [comment]
I think we would need to implement #117 to make this faster

**Comment by esheldon** [comment]
@rmjarvis does not think we can speed up the photon shooting, we making it optional and we can do targeted studies

**Comment by esheldon** [comment]
@beckermr this one should be uncontroversial

**Review by beckermr — APPROVED** [review]

**Pull request merged**
