### PR TITLE
Galaxy builder

### LINKED ISSUE #94: implement our own GalaxyBuilder to make round galaxies
This will inherit from the descwl.GalaxyBuilder and allow forcing objects to be round

this should speed up tests with gals_type 'wldeblend' significantly

### PR DESCRIPTION
**Pull request by esheldon**
Add option to make wldeblend galaxies round

closes #94

### CODE REVIEW

**Comment by esheldon** [comment]
Its hard to add detailed tests for this one, since we don't have a way to control the object s/n or the background noise.  So we can't for example test if the objects are round

**Comment by beckermr** [comment]
We can render one in the center of a sim and check that its moments matrix is symmetric.

**Comment by esheldon** [comment]
We can't do that using a Sim; do you mean to do the calls to the galaxy builder directly?

**Comment by beckermr** [comment]
Why? Just make a sim on a grid with one object.

**Comment by esheldon** [comment]
can you do grid and wldeblend?

**Comment by beckermr** [comment]
I think so yes.

**Comment by esheldon** [comment]
hmm.... travis is not running

**Comment by beckermr** [comment]
let me try something

**Pull request merged**
