### PR TITLE
implement rotations, epochs, bands

### PR DESCRIPTION
**Pull request by esheldon**

### CODE REVIEW

**Comment by esheldon** [comment]
I ran a test and this works at high s/n

**Comment by esheldon** [comment]
also checked with multiple epochs, looks ok.  So everything is lining up.

**Comment by beckermr** [comment]
What about low s/n?

**Comment by esheldon** [comment]
that will take a day or so, and needs to wait until some other runs finish

**Comment by esheldon** [comment]
(one day if the queues are friendly)

**Pull request merged**
